import path from "path";
import dotenv from "dotenv";
import { PrismaClient } from "@prisma/client";
import { createHash } from "node:crypto";

dotenv.config({ path: path.resolve(process.cwd(), "..", ".env") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

const prisma = new PrismaClient();

const hashPassword = (password: string) => createHash("sha256").update(password).digest("hex");

const getDatabaseInfo = () => {
  const url = process.env.DATABASE_URL;
  if (!url) return "DATABASE_URL manquant";
  try {
    const parsed = new URL(url);
    const user = parsed.username || "user";
    const host = parsed.host || "host";
    const db = parsed.pathname.replace("/", "") || "db";
    return `${user}@${host}/${db}`;
  } catch {
    return "DATABASE_URL invalide";
  }
};

const seed = async () => {
  // eslint-disable-next-line no-console
  console.log(`Seed démarré (${getDatabaseInfo()}).`);

  const deletedEvents = await prisma.event.deleteMany();
  const deletedCategories = await prisma.category.deleteMany();
  const deletedUsers = await prisma.user.deleteMany();

  // eslint-disable-next-line no-console
  console.log(
    `Suppression avant seed: ${deletedUsers.count} utilisateurs, ${deletedCategories.count} catégories, ${deletedEvents.count} événements.`
  );

  const usersResult = await prisma.user.createMany({
    data: [
      {
        name: "Compte Rédacteur",
        email: "editor@rene-website.local",
        role: "EDITOR",
        passwordHash: hashPassword("editor-rene-2026")
      },
      {
        name: "Compte Modérateur",
        email: "moderator@rene-website.local",
        role: "MODERATOR",
        passwordHash: hashPassword("moderator-rene-2026")
      },
      {
        name: "Compte Administrateur",
        email: "admin@rene-website.local",
        role: "ADMIN",
        passwordHash: hashPassword("admin-rene-2026")
      }
    ]
  });

  const categoriesResult = await prisma.category.createMany({
    data: [
      { id: "music", name: "Musique" },
      { id: "lecture", name: "Lecture" },
      { id: "theatre", name: "Théâtre" },
      { id: "expo", name: "Exposition" },
      { id: "cinema", name: "Cinéma" },
      { id: "festival", name: "Festival" },
      { id: "market", name: "Marché" },
      { id: "heritage", name: "Patrimoine" },
      { id: "atelier", name: "Atelier" },
      { id: "science", name: "Science" }
    ]
  });

  const eventsResult = await prisma.event.createMany({
    data: [
      {
        title: "Concert du Nouvel An",
        content: "Concert festif pour lancer l'année culturelle.",
        image: "https://source.unsplash.com/featured/?concert",
        categoryId: "music",
        eventStartAt: new Date("2026-01-18T18:00:00.000Z"),
        eventEndAt: new Date("2026-01-18T21:00:00.000Z"),
        allDay: false,
        venueName: "Salle des fêtes",
        address: "1 rue du Centre",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Ville de Descartes",
        organizerUrl: "https://descartes.fr",
        contactEmail: "culture@descartes.fr",
        contactPhone: "0247203040",
        ticketUrl: "https://billetterie.example.com/nouvelan",
        websiteUrl: "https://descartes.fr/culture",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-05T09:00:00.000Z"),
        publicationEndAt: new Date("2026-01-19T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Concert Jazz",
        content: "Soirée jazz avec trio local.",
        image: "https://source.unsplash.com/featured/?jazz",
        categoryId: "music",
        eventStartAt: new Date("2026-01-25T19:00:00.000Z"),
        eventEndAt: new Date("2026-01-25T22:00:00.000Z"),
        allDay: false,
        venueName: "Salle des fêtes",
        address: "1 rue du Centre",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Association Jazz",
        organizerUrl: "https://example.com/jazz",
        contactEmail: "contact@jazz.example.com",
        contactPhone: "0102030405",
        ticketUrl: "https://tickets.example.com/jazz",
        websiteUrl: "https://example.com/jazz",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-08T10:00:00.000Z"),
        publicationEndAt: new Date("2026-01-26T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Lecture publique",
        content: "Lecture d'auteurs locaux et échanges.",
        image: "https://source.unsplash.com/featured/?reading",
        categoryId: "lecture",
        eventStartAt: new Date("2026-02-02T14:00:00.000Z"),
        eventEndAt: new Date("2026-02-02T16:00:00.000Z"),
        allDay: false,
        venueName: "Médiathèque",
        address: "8 place de la Mairie",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.97,
        longitude: 0.71,
        organizerName: "Ville de Descartes",
        organizerUrl: null,
        contactEmail: "contact@descartes.fr",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: "https://descartes.fr",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-12T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-03T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier théâtre",
        content: "Atelier participatif pour ados.",
        image: "https://source.unsplash.com/featured/?theatre",
        categoryId: "theatre",
        eventStartAt: new Date("2026-02-07T09:00:00.000Z"),
        eventEndAt: new Date("2026-02-07T12:00:00.000Z"),
        allDay: false,
        venueName: "Maison des associations",
        address: "4 rue des Écoles",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.969,
        longitude: 0.702,
        organizerName: "Compagnie Locale",
        organizerUrl: "https://example.com/theatre",
        contactEmail: null,
        contactPhone: "0102030000",
        ticketUrl: null,
        websiteUrl: "https://example.com/theatre",
        status: "PENDING",
        publishedAt: null,
        publicationEndAt: new Date("2026-02-08T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Expo photo Loire",
        content: "Regards contemporains sur la vallée.",
        image: "https://source.unsplash.com/featured/?photo-exhibition",
        categoryId: "expo",
        eventStartAt: new Date("2026-02-10T10:00:00.000Z"),
        eventEndAt: new Date("2026-02-10T18:00:00.000Z"),
        allDay: false,
        venueName: "Galerie municipale",
        address: "2 rue de la Poste",
        postalCode: "37160",
        city: "Abilly",
        latitude: 46.971,
        longitude: 0.72,
        organizerName: "Collectif Photo",
        organizerUrl: null,
        contactEmail: "contact@photo.example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-20T10:00:00.000Z"),
        publicationEndAt: new Date("2026-02-11T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Cinéma en plein air",
        content: "Projection familiale au parc.",
        image: "https://source.unsplash.com/featured/?outdoor-cinema",
        categoryId: "cinema",
        eventStartAt: new Date("2026-02-14T19:30:00.000Z"),
        eventEndAt: new Date("2026-02-14T21:30:00.000Z"),
        allDay: false,
        venueName: "Parc communal",
        address: "Rue du Parc",
        postalCode: "37160",
        city: "Buxeuil",
        latitude: 46.96,
        longitude: 0.68,
        organizerName: "Ciné Club",
        organizerUrl: "https://cine.example.com",
        contactEmail: null,
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/cine",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-25T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-15T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Festival des arts",
        content: "Trois jours de spectacles et ateliers.",
        image: "https://source.unsplash.com/featured/?festival",
        categoryId: "festival",
        eventStartAt: new Date("2026-02-20T09:00:00.000Z"),
        eventEndAt: new Date("2026-02-22T20:00:00.000Z"),
        allDay: false,
        venueName: "Centre-ville",
        address: "Place de la Liberté",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.04,
        longitude: 0.73,
        organizerName: "Office culturel",
        organizerUrl: "https://culture.example.com",
        contactEmail: "festival@culture.example.com",
        contactPhone: "0247001122",
        ticketUrl: "https://tickets.example.com/festival",
        websiteUrl: "https://culture.example.com/festival",
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-01T10:00:00.000Z"),
        publicationEndAt: new Date("2026-02-23T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Bal folk",
        content: "Soirée dansante avec groupe local.",
        image: "https://source.unsplash.com/featured/?folk-music",
        categoryId: "music",
        eventStartAt: new Date("2026-02-27T19:00:00.000Z"),
        eventEndAt: new Date("2026-02-27T23:00:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "3 rue des Tilleuls",
        postalCode: "37350",
        city: "Le Grand-Pressigny",
        latitude: 46.93,
        longitude: 0.8,
        organizerName: "Association Folk",
        organizerUrl: null,
        contactEmail: "contact@folk.example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/folk",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-05T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-28T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Marché d'hiver",
        content: "Artisans et producteurs locaux.",
        image: "https://source.unsplash.com/featured/?market",
        categoryId: "market",
        eventStartAt: new Date("2026-03-01T08:00:00.000Z"),
        eventEndAt: new Date("2026-03-01T13:00:00.000Z"),
        allDay: false,
        venueName: "Place du marché",
        address: "Place du Marché",
        postalCode: "37240",
        city: "La Celle-Saint-Avant",
        latitude: 47.02,
        longitude: 0.58,
        organizerName: "Comité local",
        organizerUrl: null,
        contactEmail: null,
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-10T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-02T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Soirée poésie",
        content: "Scène ouverte poétique.",
        image: "https://source.unsplash.com/featured/?poetry",
        categoryId: "lecture",
        eventStartAt: new Date("2026-03-05T18:30:00.000Z"),
        eventEndAt: new Date("2026-03-05T20:30:00.000Z"),
        allDay: false,
        venueName: "Maison des arts",
        address: "12 rue du Pont",
        postalCode: "37240",
        city: "Draché",
        latitude: 47.08,
        longitude: 0.5,
        organizerName: "Poètes en scène",
        organizerUrl: null,
        contactEmail: "poesie@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-06T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Théâtre de rue",
        content: "Spectacle itinérant en centre-bourg.",
        image: "https://source.unsplash.com/featured/?street-theatre",
        categoryId: "theatre",
        eventStartAt: new Date("2026-03-08T17:00:00.000Z"),
        eventEndAt: new Date("2026-03-08T19:00:00.000Z"),
        allDay: false,
        venueName: "Centre-bourg",
        address: "Rue principale",
        postalCode: "37350",
        city: "Paulmy",
        latitude: 46.93,
        longitude: 0.72,
        organizerName: "Compagnie Itinérante",
        organizerUrl: "https://compagnie.example.com",
        contactEmail: "contact@compagnie.example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: "https://compagnie.example.com",
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-20T10:00:00.000Z"),
        publicationEndAt: new Date("2026-03-09T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Nuit du patrimoine",
        content: "Visites guidées et concerts dans la nuit.",
        image: "https://source.unsplash.com/featured/?heritage",
        categoryId: "heritage",
        eventStartAt: new Date("2026-03-14T18:00:00.000Z"),
        eventEndAt: new Date("2026-03-14T23:00:00.000Z"),
        allDay: false,
        venueName: "Château",
        address: "Route du Château",
        postalCode: "37160",
        city: "Neuilly-le-Brignon",
        latitude: 46.9,
        longitude: 0.58,
        organizerName: "Association Patrimoine",
        organizerUrl: null,
        contactEmail: "patrimoine@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/patrimoine",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-25T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-15T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Concert classique",
        content: "Quatuor à cordes au jardin.",
        image: "https://source.unsplash.com/featured/?classical-music",
        categoryId: "music",
        eventStartAt: new Date("2026-03-20T18:30:00.000Z"),
        eventEndAt: new Date("2026-03-20T20:30:00.000Z"),
        allDay: false,
        venueName: "Jardin municipal",
        address: "Avenue du Parc",
        postalCode: "86270",
        city: "La Roche-Posay",
        latitude: 46.79,
        longitude: 0.82,
        organizerName: "Académie de musique",
        organizerUrl: null,
        contactEmail: "musique@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/classique",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-21T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier peinture",
        content: "Initiation à l'aquarelle pour tous.",
        image: "https://source.unsplash.com/featured/?watercolor",
        categoryId: "atelier",
        eventStartAt: new Date("2026-03-24T09:00:00.000Z"),
        eventEndAt: new Date("2026-03-24T12:00:00.000Z"),
        allDay: false,
        venueName: "Salle des ateliers",
        address: "5 rue des Arts",
        postalCode: "37240",
        city: "Bournan",
        latitude: 46.89,
        longitude: 0.6,
        organizerName: "Ateliers créatifs",
        organizerUrl: null,
        contactEmail: "atelier@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-05T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-25T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Salon du livre",
        content: "Rencontres, dédicaces et ateliers.",
        image: "https://source.unsplash.com/featured/?book-fair",
        categoryId: "lecture",
        eventStartAt: new Date("2026-03-28T09:00:00.000Z"),
        eventEndAt: new Date("2026-03-28T18:00:00.000Z"),
        allDay: false,
        venueName: "Halle municipale",
        address: "Rue des Halles",
        postalCode: "37290",
        city: "Preuilly-sur-Claise",
        latitude: 46.85,
        longitude: 0.93,
        organizerName: "Association Lecture",
        organizerUrl: null,
        contactEmail: "livre@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-10T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-29T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Projection documentaire",
        content: "Échanges avec le réalisateur après la séance.",
        image: "https://source.unsplash.com/featured/?documentary",
        categoryId: "cinema",
        eventStartAt: new Date("2026-04-02T19:00:00.000Z"),
        eventEndAt: new Date("2026-04-02T21:00:00.000Z"),
        allDay: false,
        venueName: "Cinéma local",
        address: "12 rue du Cinéma",
        postalCode: "37240",
        city: "Sepmes",
        latitude: 46.84,
        longitude: 0.78,
        organizerName: "Ciné Club",
        organizerUrl: null,
        contactEmail: "docu@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/docu",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-12T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-03T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Fête de la science",
        content: "Ateliers et démonstrations pour tous.",
        image: "https://source.unsplash.com/featured/?science",
        categoryId: "science",
        eventStartAt: new Date("2026-04-05T09:00:00.000Z"),
        eventEndAt: new Date("2026-04-05T17:00:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "Rue des Écoles",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.971,
        longitude: 0.706,
        organizerName: "Réseau scientifique",
        organizerUrl: null,
        contactEmail: "science@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-06T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Spectacle jeune public",
        content: "Conte musical pour enfants.",
        image: "https://source.unsplash.com/featured/?kids-theatre",
        categoryId: "theatre",
        eventStartAt: new Date("2026-04-10T14:00:00.000Z"),
        eventEndAt: new Date("2026-04-10T15:30:00.000Z"),
        allDay: false,
        venueName: "Espace culturel",
        address: "10 avenue des Sports",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.041,
        longitude: 0.728,
        organizerName: "Compagnie Junior",
        organizerUrl: null,
        contactEmail: null,
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/jeunepublic",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-20T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-11T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Rencontre BD",
        content: "Dédicaces et ateliers dessin.",
        image: "https://source.unsplash.com/featured/?comics",
        categoryId: "lecture",
        eventStartAt: new Date("2026-04-12T10:00:00.000Z"),
        eventEndAt: new Date("2026-04-12T17:00:00.000Z"),
        allDay: false,
        venueName: "Médiathèque",
        address: "8 place de la Mairie",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.97,
        longitude: 0.71,
        organizerName: "BD en Touraine",
        organizerUrl: null,
        contactEmail: "bd@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-22T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-13T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Marché de printemps",
        content: "Artisanat local et gourmandises de saison.",
        image: "https://source.unsplash.com/featured/?spring-market",
        categoryId: "market",
        eventStartAt: new Date("2026-04-18T09:00:00.000Z"),
        eventEndAt: new Date("2026-04-18T18:00:00.000Z"),
        allDay: false,
        venueName: "Place centrale",
        address: "Place centrale",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.973,
        longitude: 0.704,
        organizerName: "Comité des fêtes",
        organizerUrl: null,
        contactEmail: "noel@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-28T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-19T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Matinée chorale",
        content: "Chants sacrés et polyphonies régionales.",
        image: "https://source.unsplash.com/featured/?choir",
        categoryId: "music",
        eventStartAt: new Date("2026-01-20T10:00:00.000Z"),
        eventEndAt: new Date("2026-01-20T12:00:00.000Z"),
        allDay: false,
        venueName: "Église Saint-Georges",
        address: "Place de l'Église",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Chorale de Touraine",
        organizerUrl: null,
        contactEmail: "chorale@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-06T09:00:00.000Z"),
        publicationEndAt: new Date("2026-01-21T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Ciné-débat",
        content: "Projection suivie d'un échange avec des intervenants.",
        image: "https://source.unsplash.com/featured/?cinema",
        categoryId: "cinema",
        eventStartAt: new Date("2026-01-23T20:00:00.000Z"),
        eventEndAt: new Date("2026-01-23T22:00:00.000Z"),
        allDay: false,
        venueName: "Cinéma local",
        address: "12 rue du Cinéma",
        postalCode: "37240",
        city: "Sepmes",
        latitude: 46.84,
        longitude: 0.78,
        organizerName: "Ciné Club",
        organizerUrl: null,
        contactEmail: "cine@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/cinedebat",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-08T09:00:00.000Z"),
        publicationEndAt: new Date("2026-01-24T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier céramique",
        content: "Initiation au tournage et à l'émaillage.",
        image: "https://source.unsplash.com/featured/?ceramics",
        categoryId: "atelier",
        eventStartAt: new Date("2026-01-29T09:00:00.000Z"),
        eventEndAt: new Date("2026-01-29T12:00:00.000Z"),
        allDay: false,
        venueName: "Salle des ateliers",
        address: "5 rue des Arts",
        postalCode: "37240",
        city: "Bournan",
        latitude: 46.89,
        longitude: 0.6,
        organizerName: "Ateliers créatifs",
        organizerUrl: null,
        contactEmail: "ceramique@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-12T09:00:00.000Z"),
        publicationEndAt: new Date("2026-01-30T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Expo artisans d'art",
        content: "Créations locales et démonstrations de savoir-faire.",
        image: "https://source.unsplash.com/featured/?crafts",
        categoryId: "expo",
        eventStartAt: new Date("2026-02-03T10:00:00.000Z"),
        eventEndAt: new Date("2026-02-03T17:00:00.000Z"),
        allDay: false,
        venueName: "Galerie municipale",
        address: "2 rue de la Poste",
        postalCode: "37160",
        city: "Abilly",
        latitude: 46.971,
        longitude: 0.72,
        organizerName: "Maison des métiers d'art",
        organizerUrl: null,
        contactEmail: "metiersdart@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-15T10:00:00.000Z"),
        publicationEndAt: new Date("2026-02-04T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Café philo",
        content: "Débat ouvert autour d'un thème mensuel.",
        image: "https://source.unsplash.com/featured/?philosophy",
        categoryId: "lecture",
        eventStartAt: new Date("2026-02-05T18:00:00.000Z"),
        eventEndAt: new Date("2026-02-05T20:00:00.000Z"),
        allDay: false,
        venueName: "Café des Arcades",
        address: "6 place de la Liberté",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.04,
        longitude: 0.73,
        organizerName: "Association Lecture",
        organizerUrl: null,
        contactEmail: "philo@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-16T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-06T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Rando patrimoine",
        content: "Balade commentée autour du patrimoine local.",
        image: "https://source.unsplash.com/featured/?hiking",
        categoryId: "heritage",
        eventStartAt: new Date("2026-02-11T00:00:00.000Z"),
        eventEndAt: new Date("2026-02-11T23:59:00.000Z"),
        allDay: true,
        venueName: "Point de départ mairie",
        address: "Place de la Mairie",
        postalCode: "37160",
        city: "Neuilly-le-Brignon",
        latitude: 46.9,
        longitude: 0.58,
        organizerName: "Association Patrimoine",
        organizerUrl: null,
        contactEmail: "rando@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-20T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-12T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Stage théâtre",
        content: "Deux journées d'initiation au jeu scénique.",
        image: "https://source.unsplash.com/featured/?acting",
        categoryId: "theatre",
        eventStartAt: new Date("2026-02-16T09:00:00.000Z"),
        eventEndAt: new Date("2026-02-16T17:00:00.000Z"),
        allDay: false,
        venueName: "Espace culturel",
        address: "10 avenue des Sports",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.041,
        longitude: 0.728,
        organizerName: "Compagnie Locale",
        organizerUrl: "https://example.com/theatre",
        contactEmail: "stage@example.com",
        contactPhone: "0247002233",
        ticketUrl: "https://tickets.example.com/stage",
        websiteUrl: "https://example.com/theatre",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-25T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-17T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Soirée électro",
        content: "Set DJ et ambiance club pour la jeunesse locale.",
        image: "https://source.unsplash.com/featured/?electronic-music",
        categoryId: "music",
        eventStartAt: new Date("2026-02-18T20:00:00.000Z"),
        eventEndAt: new Date("2026-02-18T23:30:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "3 rue des Tilleuls",
        postalCode: "37350",
        city: "Le Grand-Pressigny",
        latitude: 46.93,
        longitude: 0.8,
        organizerName: "Collectif Electro",
        organizerUrl: null,
        contactEmail: "electro@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/electro",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-19T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Marché de créateurs",
        content: "Sélection d'artisans, bijoux et objets uniques.",
        image: "https://source.unsplash.com/featured/?makers-market",
        categoryId: "market",
        eventStartAt: new Date("2026-02-21T09:00:00.000Z"),
        eventEndAt: new Date("2026-02-21T17:00:00.000Z"),
        allDay: false,
        venueName: "Place du marché",
        address: "Place du Marché",
        postalCode: "37240",
        city: "La Celle-Saint-Avant",
        latitude: 47.02,
        longitude: 0.58,
        organizerName: "Comité local",
        organizerUrl: null,
        contactEmail: "createurs@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-02T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-22T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier photo",
        content: "Techniques de prise de vue en lumière naturelle.",
        image: "https://source.unsplash.com/featured/?photography",
        categoryId: "atelier",
        eventStartAt: new Date("2026-02-24T14:00:00.000Z"),
        eventEndAt: new Date("2026-02-24T17:00:00.000Z"),
        allDay: false,
        venueName: "Maison des arts",
        address: "12 rue du Pont",
        postalCode: "37240",
        city: "Draché",
        latitude: 47.08,
        longitude: 0.5,
        organizerName: "Collectif Photo",
        organizerUrl: null,
        contactEmail: "photo@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-05T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-25T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Rencontre scientifique",
        content: "Présentation vulgarisée et questions du public.",
        image: "https://source.unsplash.com/featured/?science-talk",
        categoryId: "science",
        eventStartAt: new Date("2026-03-02T18:00:00.000Z"),
        eventEndAt: new Date("2026-03-02T20:00:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "Rue des Écoles",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.971,
        longitude: 0.706,
        organizerName: "Réseau scientifique",
        organizerUrl: null,
        contactEmail: "rencontre.science@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-10T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-03T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Projection court-métrage",
        content: "Sélection locale suivie d'un échange convivial.",
        image: "https://source.unsplash.com/featured/?short-film",
        categoryId: "cinema",
        eventStartAt: new Date("2026-03-06T19:00:00.000Z"),
        eventEndAt: new Date("2026-03-06T21:00:00.000Z"),
        allDay: false,
        venueName: "Cinéma local",
        address: "12 rue du Cinéma",
        postalCode: "37240",
        city: "Sepmes",
        latitude: 46.84,
        longitude: 0.78,
        organizerName: "Ciné Club",
        organizerUrl: null,
        contactEmail: "courtmetrage@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/courts",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-12T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-07T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Concert chorale",
        content: "Programme classique et chants du monde.",
        image: "https://source.unsplash.com/featured/?choral",
        categoryId: "music",
        eventStartAt: new Date("2026-03-12T19:00:00.000Z"),
        eventEndAt: new Date("2026-03-12T21:00:00.000Z"),
        allDay: false,
        venueName: "Salle des fêtes",
        address: "1 rue du Centre",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Chorale de Touraine",
        organizerUrl: null,
        contactEmail: "concertchorale@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/chorale",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-20T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-13T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Visite guidée du château",
        content: "Parcours commenté et anecdotes historiques.",
        image: "https://source.unsplash.com/featured/?castle",
        categoryId: "heritage",
        eventStartAt: new Date("2026-03-18T15:00:00.000Z"),
        eventEndAt: new Date("2026-03-18T17:00:00.000Z"),
        allDay: false,
        venueName: "Château",
        address: "Route du Château",
        postalCode: "37160",
        city: "Neuilly-le-Brignon",
        latitude: 46.9,
        longitude: 0.58,
        organizerName: "Association Patrimoine",
        organizerUrl: null,
        contactEmail: "visite@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/visite",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-25T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-19T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Bourse aux livres",
        content: "Achat, vente et échange de livres d'occasion.",
        image: "https://source.unsplash.com/featured/?used-books",
        categoryId: "lecture",
        eventStartAt: new Date("2026-03-26T09:00:00.000Z"),
        eventEndAt: new Date("2026-03-26T16:00:00.000Z"),
        allDay: false,
        venueName: "Halle municipale",
        address: "Rue des Halles",
        postalCode: "37290",
        city: "Preuilly-sur-Claise",
        latitude: 46.85,
        longitude: 0.93,
        organizerName: "Association Lecture",
        organizerUrl: null,
        contactEmail: "bourse@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-05T09:00:00.000Z"),
        publicationEndAt: new Date("2026-03-27T00:00:00.000Z"),
        rejectionReason: null
      }
    ]
  });

  // eslint-disable-next-line no-console
  console.log(
    `Seed terminé: ${usersResult.count} utilisateurs, ${categoriesResult.count} catégories, ${eventsResult.count} événements.`
  );
};

seed()
  .catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
