import path from "path";
import dotenv from "dotenv";
import { PrismaClient } from "@prisma/client";
import { createHash } from "node:crypto";

dotenv.config({ path: path.resolve(process.cwd(), "..", ".env") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

const prisma = new PrismaClient();

const hashPassword = (password: string) => createHash("sha256").update(password).digest("hex");

const getDatabaseInfo = () => {
  const url = process.env.DATABASE_URL;
  if (!url) return "DATABASE_URL manquant";
  try {
    const parsed = new URL(url);
    const user = parsed.username || "user";
    const host = parsed.host || "host";
    const db = parsed.pathname.replace("/", "") || "db";
    return `${user}@${host}/${db}`;
  } catch {
    return "DATABASE_URL invalide";
  }
};

const seed = async () => {
  // eslint-disable-next-line no-console
  console.log(`Seed démarré (${getDatabaseInfo()}).`);

  const deletedEvents = await prisma.event.deleteMany();
  const deletedUsers = await prisma.user.deleteMany();

  // eslint-disable-next-line no-console
  console.log(`Suppression avant seed: ${deletedUsers.count} utilisateurs, ${deletedEvents.count} événements.`);

  const usersResult = await prisma.user.createMany({
    data: [
      {
        name: "Compte Rédacteur",
        email: "editor@rene-website.local",
        role: "EDITOR",
        passwordHash: hashPassword("editor-rene-2026")
      },
      {
        name: "Compte Modérateur",
        email: "moderator@rene-website.local",
        role: "MODERATOR",
        passwordHash: hashPassword("moderator-rene-2026")
      },
      {
        name: "Compte Administrateur",
        email: "admin@rene-website.local",
        role: "ADMIN",
        passwordHash: hashPassword("admin-rene-2026")
      }
    ]
  });

  const eventsResult = await prisma.event.createMany({
    data: [
      {
        title: "Concert du Nouvel An",
        content: "Concert festif pour lancer l'année culturelle.",
        image: "https://images.example.com/newyear.jpg",
        categoryId: "music",
        eventStartAt: new Date("2026-01-10T18:00:00.000Z"),
        eventEndAt: new Date("2026-01-10T21:00:00.000Z"),
        allDay: false,
        venueName: "Salle des fêtes",
        address: "1 rue du Centre",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Ville de Descartes",
        organizerUrl: "https://descartes.fr",
        contactEmail: "culture@descartes.fr",
        contactPhone: "0247203040",
        ticketUrl: "https://billetterie.example.com/nouvelan",
        websiteUrl: "https://descartes.fr/culture",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-02T09:00:00.000Z"),
        publicationEndAt: new Date("2026-01-11T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Concert Jazz",
        content: "Soirée jazz avec trio local.",
        image: "https://images.example.com/jazz.jpg",
        categoryId: "music",
        eventStartAt: new Date("2026-02-01T19:00:00.000Z"),
        eventEndAt: new Date("2026-02-01T22:00:00.000Z"),
        allDay: false,
        venueName: "Salle des fêtes",
        address: "1 rue du Centre",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.972,
        longitude: 0.705,
        organizerName: "Association Jazz",
        organizerUrl: "https://example.com/jazz",
        contactEmail: "contact@jazz.example.com",
        contactPhone: "0102030405",
        ticketUrl: "https://tickets.example.com/jazz",
        websiteUrl: "https://example.com/jazz",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-10T10:00:00.000Z"),
        publicationEndAt: new Date("2026-02-02T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Lecture publique",
        content: "Lecture d'auteurs locaux et échanges.",
        image: "https://images.example.com/lecture.jpg",
        categoryId: "lecture",
        eventStartAt: new Date("2026-02-08T14:00:00.000Z"),
        eventEndAt: new Date("2026-02-08T16:00:00.000Z"),
        allDay: false,
        venueName: "Médiathèque",
        address: "8 place de la Mairie",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.97,
        longitude: 0.71,
        organizerName: "Ville de Descartes",
        organizerUrl: null,
        contactEmail: "contact@descartes.fr",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: "https://descartes.fr",
        status: "PUBLISHED",
        publishedAt: new Date("2026-01-12T09:00:00.000Z"),
        publicationEndAt: new Date("2026-02-09T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier théâtre",
        content: "Atelier participatif pour ados.",
        image: "https://images.example.com/theatre.jpg",
        categoryId: "theatre",
        eventStartAt: new Date("2026-02-15T09:00:00.000Z"),
        eventEndAt: new Date("2026-02-15T12:00:00.000Z"),
        allDay: false,
        venueName: "Maison des associations",
        address: "4 rue des Écoles",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.969,
        longitude: 0.702,
        organizerName: "Compagnie Locale",
        organizerUrl: "https://example.com/theatre",
        contactEmail: null,
        contactPhone: "0102030000",
        ticketUrl: null,
        websiteUrl: "https://example.com/theatre",
        status: "PENDING",
        publishedAt: null,
        publicationEndAt: new Date("2026-02-16T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Expo photo Loire",
        content: "Regards contemporains sur la vallée.",
        image: "https://images.example.com/expo-photo.jpg",
        categoryId: "expo",
        eventStartAt: new Date("2026-03-05T10:00:00.000Z"),
        eventEndAt: new Date("2026-03-05T18:00:00.000Z"),
        allDay: false,
        venueName: "Galerie municipale",
        address: "2 rue de la Poste",
        postalCode: "37160",
        city: "Abilly",
        latitude: 46.971,
        longitude: 0.72,
        organizerName: "Collectif Photo",
        organizerUrl: null,
        contactEmail: "contact@photo.example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-02-20T10:00:00.000Z"),
        publicationEndAt: new Date("2026-03-06T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Cinéma en plein air",
        content: "Projection familiale au parc.",
        image: "https://images.example.com/cinema.jpg",
        categoryId: "cinema",
        eventStartAt: new Date("2026-04-12T19:30:00.000Z"),
        eventEndAt: new Date("2026-04-12T21:30:00.000Z"),
        allDay: false,
        venueName: "Parc communal",
        address: "Rue du Parc",
        postalCode: "37160",
        city: "Buxeuil",
        latitude: 46.96,
        longitude: 0.68,
        organizerName: "Ciné Club",
        organizerUrl: "https://cine.example.com",
        contactEmail: null,
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/cine",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-03-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-04-13T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Festival des arts",
        content: "Trois jours de spectacles et ateliers.",
        image: "https://images.example.com/festival.jpg",
        categoryId: "festival",
        eventStartAt: new Date("2026-05-01T09:00:00.000Z"),
        eventEndAt: new Date("2026-05-03T20:00:00.000Z"),
        allDay: false,
        venueName: "Centre-ville",
        address: "Place de la Liberté",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.04,
        longitude: 0.73,
        organizerName: "Office culturel",
        organizerUrl: "https://culture.example.com",
        contactEmail: "festival@culture.example.com",
        contactPhone: "0247001122",
        ticketUrl: "https://tickets.example.com/festival",
        websiteUrl: "https://culture.example.com/festival",
        status: "PUBLISHED",
        publishedAt: new Date("2026-04-01T10:00:00.000Z"),
        publicationEndAt: new Date("2026-05-04T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Bal folk",
        content: "Soirée dansante avec groupe local.",
        image: "https://images.example.com/folk.jpg",
        categoryId: "music",
        eventStartAt: new Date("2026-05-22T19:00:00.000Z"),
        eventEndAt: new Date("2026-05-22T23:00:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "3 rue des Tilleuls",
        postalCode: "37350",
        city: "Le Grand-Pressigny",
        latitude: 46.93,
        longitude: 0.8,
        organizerName: "Association Folk",
        organizerUrl: null,
        contactEmail: "contact@folk.example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/folk",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-05-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-05-23T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Marché d'été",
        content: "Artisans et producteurs locaux.",
        image: "https://images.example.com/marche.jpg",
        categoryId: "market",
        eventStartAt: new Date("2026-06-07T08:00:00.000Z"),
        eventEndAt: new Date("2026-06-07T13:00:00.000Z"),
        allDay: false,
        venueName: "Place du marché",
        address: "Place du Marché",
        postalCode: "37240",
        city: "La Celle-Saint-Avant",
        latitude: 47.02,
        longitude: 0.58,
        organizerName: "Comité local",
        organizerUrl: null,
        contactEmail: null,
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-05-10T09:00:00.000Z"),
        publicationEndAt: new Date("2026-06-08T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Soirée poésie",
        content: "Scène ouverte poétique.",
        image: "https://images.example.com/poesie.jpg",
        categoryId: "lecture",
        eventStartAt: new Date("2026-06-20T18:30:00.000Z"),
        eventEndAt: new Date("2026-06-20T20:30:00.000Z"),
        allDay: false,
        venueName: "Maison des arts",
        address: "12 rue du Pont",
        postalCode: "37240",
        city: "Draché",
        latitude: 47.08,
        longitude: 0.5,
        organizerName: "Poètes en scène",
        organizerUrl: null,
        contactEmail: "poesie@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-06-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-06-21T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Théâtre de rue",
        content: "Spectacle itinérant en centre-bourg.",
        image: "https://images.example.com/street-theatre.jpg",
        categoryId: "theatre",
        eventStartAt: new Date("2026-07-10T17:00:00.000Z"),
        eventEndAt: new Date("2026-07-10T19:00:00.000Z"),
        allDay: false,
        venueName: "Centre-bourg",
        address: "Rue principale",
        postalCode: "37350",
        city: "Paulmy",
        latitude: 46.93,
        longitude: 0.72,
        organizerName: "Compagnie Itinérante",
        organizerUrl: "https://compagnie.example.com",
        contactEmail: "contact@compagnie.example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: "https://compagnie.example.com",
        status: "PUBLISHED",
        publishedAt: new Date("2026-06-20T10:00:00.000Z"),
        publicationEndAt: new Date("2026-07-11T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Nuit du patrimoine",
        content: "Visites guidées et concerts dans la nuit.",
        image: "https://images.example.com/heritage.jpg",
        categoryId: "heritage",
        eventStartAt: new Date("2026-07-24T18:00:00.000Z"),
        eventEndAt: new Date("2026-07-24T23:00:00.000Z"),
        allDay: false,
        venueName: "Château",
        address: "Route du Château",
        postalCode: "37160",
        city: "Neuilly-le-Brignon",
        latitude: 46.9,
        longitude: 0.58,
        organizerName: "Association Patrimoine",
        organizerUrl: null,
        contactEmail: "patrimoine@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/patrimoine",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-07-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-07-25T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Concert classique",
        content: "Quatuor à cordes au jardin.",
        image: "https://images.example.com/classic.jpg",
        categoryId: "music",
        eventStartAt: new Date("2026-08-05T18:30:00.000Z"),
        eventEndAt: new Date("2026-08-05T20:30:00.000Z"),
        allDay: false,
        venueName: "Jardin municipal",
        address: "Avenue du Parc",
        postalCode: "86270",
        city: "La Roche-Posay",
        latitude: 46.79,
        longitude: 0.82,
        organizerName: "Académie de musique",
        organizerUrl: null,
        contactEmail: "musique@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/classique",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-07-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-08-06T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Atelier peinture",
        content: "Initiation à l'aquarelle pour tous.",
        image: "https://images.example.com/painting.jpg",
        categoryId: "atelier",
        eventStartAt: new Date("2026-08-16T09:00:00.000Z"),
        eventEndAt: new Date("2026-08-16T12:00:00.000Z"),
        allDay: false,
        venueName: "Salle des ateliers",
        address: "5 rue des Arts",
        postalCode: "37240",
        city: "Bournan",
        latitude: 46.89,
        longitude: 0.6,
        organizerName: "Ateliers créatifs",
        organizerUrl: null,
        contactEmail: "atelier@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-08-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-08-17T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Salon du livre",
        content: "Rencontres, dédicaces et ateliers.",
        image: "https://images.example.com/bookfair.jpg",
        categoryId: "lecture",
        eventStartAt: new Date("2026-09-06T09:00:00.000Z"),
        eventEndAt: new Date("2026-09-06T18:00:00.000Z"),
        allDay: false,
        venueName: "Halle municipale",
        address: "Rue des Halles",
        postalCode: "37290",
        city: "Preuilly-sur-Claise",
        latitude: 46.85,
        longitude: 0.93,
        organizerName: "Association Lecture",
        organizerUrl: null,
        contactEmail: "livre@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-08-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-09-07T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Projection documentaire",
        content: "Échanges avec le réalisateur après la séance.",
        image: "https://images.example.com/docu.jpg",
        categoryId: "cinema",
        eventStartAt: new Date("2026-09-19T19:00:00.000Z"),
        eventEndAt: new Date("2026-09-19T21:00:00.000Z"),
        allDay: false,
        venueName: "Cinéma local",
        address: "12 rue du Cinéma",
        postalCode: "37240",
        city: "Sepmes",
        latitude: 46.84,
        longitude: 0.78,
        organizerName: "Ciné Club",
        organizerUrl: null,
        contactEmail: "docu@example.com",
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/docu",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-09-01T09:00:00.000Z"),
        publicationEndAt: new Date("2026-09-20T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Fête de la science",
        content: "Ateliers et démonstrations pour tous.",
        image: "https://images.example.com/science.jpg",
        categoryId: "science",
        eventStartAt: new Date("2026-10-03T09:00:00.000Z"),
        eventEndAt: new Date("2026-10-03T17:00:00.000Z"),
        allDay: false,
        venueName: "Salle polyvalente",
        address: "Rue des Écoles",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.971,
        longitude: 0.706,
        organizerName: "Réseau scientifique",
        organizerUrl: null,
        contactEmail: "science@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-09-10T09:00:00.000Z"),
        publicationEndAt: new Date("2026-10-04T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Spectacle jeune public",
        content: "Conte musical pour enfants.",
        image: "https://images.example.com/kids.jpg",
        categoryId: "theatre",
        eventStartAt: new Date("2026-10-17T14:00:00.000Z"),
        eventEndAt: new Date("2026-10-17T15:30:00.000Z"),
        allDay: false,
        venueName: "Espace culturel",
        address: "10 avenue des Sports",
        postalCode: "37240",
        city: "Ligueil",
        latitude: 47.041,
        longitude: 0.728,
        organizerName: "Compagnie Junior",
        organizerUrl: null,
        contactEmail: null,
        contactPhone: null,
        ticketUrl: "https://tickets.example.com/jeunepublic",
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-09-25T09:00:00.000Z"),
        publicationEndAt: new Date("2026-10-18T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Rencontre BD",
        content: "Dédicaces et ateliers dessin.",
        image: "https://images.example.com/bd.jpg",
        categoryId: "lecture",
        eventStartAt: new Date("2026-11-08T10:00:00.000Z"),
        eventEndAt: new Date("2026-11-08T17:00:00.000Z"),
        allDay: false,
        venueName: "Médiathèque",
        address: "8 place de la Mairie",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.97,
        longitude: 0.71,
        organizerName: "BD en Touraine",
        organizerUrl: null,
        contactEmail: "bd@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-10-15T09:00:00.000Z"),
        publicationEndAt: new Date("2026-11-09T00:00:00.000Z"),
        rejectionReason: null
      },
      {
        title: "Marché de Noël",
        content: "Artisanat et gourmandises de fin d'année.",
        image: "https://images.example.com/noel.jpg",
        categoryId: "market",
        eventStartAt: new Date("2026-12-12T09:00:00.000Z"),
        eventEndAt: new Date("2026-12-12T18:00:00.000Z"),
        allDay: false,
        venueName: "Place centrale",
        address: "Place centrale",
        postalCode: "37160",
        city: "Descartes",
        latitude: 46.973,
        longitude: 0.704,
        organizerName: "Comité des fêtes",
        organizerUrl: null,
        contactEmail: "noel@example.com",
        contactPhone: null,
        ticketUrl: null,
        websiteUrl: null,
        status: "PUBLISHED",
        publishedAt: new Date("2026-11-20T09:00:00.000Z"),
        publicationEndAt: new Date("2026-12-13T00:00:00.000Z"),
        rejectionReason: null
      }
    ]
  });

  // eslint-disable-next-line no-console
  console.log(`Seed terminé: ${usersResult.count} utilisateurs, ${eventsResult.count} événements.`);
};

seed()
  .catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
